<script setup lang="ts">
import DatePicker from 'primevue/datepicker'
import { useToast } from 'primevue/usetoast'
import { computed, onMounted, ref } from 'vue'

definePageMeta({
  middleware: ['auth'],
})

const pb = usePocketBase()
const toast = useToast()

const authStore = useAuthStore()
const filtersStore = useFiltersStore()

const title = ref('')
const selectedIdols = ref<any[]>([])
const selectedGroups = ref<any[]>([])
const selectedTags = ref<any[]>([])
const selectedFileType = ref<any[]>([])
const selectedDate = ref<Date | null>(null)
const source = ref('')

const autoGeneratedTitle = computed(() => {
  if (!selectedIdols.value.length && !selectedGroups.value.length) {
    return 'Title...'
  }
  else {
    const idolNames = selectedIdols.value.map(idol => idol.name).join(', ')
    const groupNames = selectedGroups.value.map(group => group.name).join(', ')

    return idolNames && groupNames
      ? `${idolNames} from ${groupNames}`
      : idolNames || groupNames
  }
})

async function customUploader(event: any) {
  const files = Array.isArray(event.files) ? event.files : [event.files]
  let setId: string | null = null
  if (!pb.authStore.isSuperuser) {
    toast.add({ severity: 'error', summary: 'Error', detail: 'You must be verified user to upload files.', life: 3000 })
    return
  }

  // If more than one file is being uploaded, create a new set
  if (files.length > 1) {
    try {
      const setData = {
        title: title.value || autoGeneratedTitle.value,
        idol: selectedIdols.value.map(idol => idol.id),
        group: selectedGroups.value.map(group => group.id),
        uploader: [authStore.uploader?.id],
      }

      const setRecord = await pb.collection('contents_sets').create(setData)
      setId = setRecord.id
      toast.add({ severity: 'success', summary: 'Set Created', detail: `Set "${setData.title}" created successfully!`, life: 3000 })
    }
    catch (error) {
      toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to create set.', life: 3000 })
      return
    }
  }

  // Iterate over each file and create a separate record
  for (const file of files) {
    const formData = new FormData()
    formData.append('file', file)

    formData.append('title', title.value || autoGeneratedTitle.value)
    formData.append('source', source.value)
    formData.append('filetype', selectedFileType.value as any)

    selectedIdols.value.forEach((idol) => {
      formData.append('idol', idol.id)
    })
    selectedGroups.value.forEach((group) => {
      formData.append('group', group.id)
    })
    selectedTags.value.forEach((tag) => {
      formData.append('tag', tag.id)
    })

    if (authStore.uploader?.id) {
      formData.append('uploader', authStore.uploader.id)
    }

    if (selectedDate.value) {
      formData.append('date', selectedDate.value.toISOString())
    }
    else {
      formData.append('date', new Date().toISOString())
    }

    // Add the set ID to formData if a set was created
    if (setId) {
      formData.append('set', setId)
    }

    try {
      await pb.collection('contents').create(formData)
      toast.add({ severity: 'success', summary: 'Success', detail: `File "${file.name}" uploaded successfully!`, life: 3000 })
    }
    catch (error) {
      toast.add({ severity: 'error', summary: 'Error', detail: `Failed to upload file "${file.name}".`, life: 3000 })
    }
  }

  // Clear the FileUpload component after processing all files
  const fileUpload = document.getElementById('fileUpload') as any
  if (fileUpload && fileUpload.clear) {
    fileUpload.clear()
  }
}

function onError(event: any) {
  console.error('Upload Error:', event)
  toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to upload files.', life: 3000 })
}

onMounted(async () => {
  filtersStore.refetchFiltersData()
})
</script>

<template>
  <div>
    <NavigationUploads class="mt-6" />

    <div class="bg-gray-700 p-6 min-h-200 border-dashed	border-2 border-red-500 rounded-lg">
      <h1 class="text-center text-5xl text-red-500 font-bold">
        WORK IN PROGRESS
      </h1>
      <p class="text-center text-xl text-red-500 italic">
        unavailable for standard users
      </p>
      <div class="flex gap-4 items-stretch">
        <div class="flex-1">
          <h2 class="text-4xl text-center">
            Metadata
          </h2>

          <div class="flex flex-col gap-3">
            <div class="flex flex-col">
              <label for="idols">Idols</label>
              <MultiSelect v-model="selectedIdols" :options="filtersStore.idols" option-label="name" placeholder="Select idols..." />
            </div>

            <div class="flex flex-col">
              <label for="groups">Groups</label>
              <MultiSelect v-model="selectedGroups" :options="filtersStore.groups" option-label="name" placeholder="Select groups..." />
            </div>

            <div class="flex flex-col">
              <label for="title">Title</label>
              <InputText id="title" v-model="title" :placeholder="autoGeneratedTitle" />
            </div>

            <div class="flex flex-col">
              <label for="tags">Tags</label>
              <MultiSelect v-model="selectedTags" :options="filtersStore.tags" option-label="name" placeholder="Select tags..." />
            </div>

            <div class="flex flex-col">
              <label for="date">Date</label>
              <DatePicker v-model="selectedDate" selection-mode="single" :manual-input="false" placeholder="Select date..." />
            </div>

            <div class="flex flex-col">
              <label for="source">Source</label>
              <InputText id="source" v-model="source" placeholder="Youtube, Instagram, Weverse..." />
            </div>
          </div>
        </div>
        <div class="flex-1">
          <h2 class="text-4xl text-center mb-5">
            Files
          </h2>

          <FileUpload
            ref="fileUpload"
            name="file"
            :custom-upload="true"
            :multiple="true"
            accept="image/*, video/*"
            :auto="false"
            :max-file-size="10000000"
            @uploader="customUploader"
            @error="onError"
          >
            <template #empty>
              <div class="flex justify-center">
                <div class="flex items-center justify-center flex-col">
                  <i class="pi pi-cloud-upload !border-2 !rounded-full !p-8 !text-4xl !text-muted-color" />
                  <p class="mt-6 mb-0">
                    Drag and drop files to here to upload.
                  </p>
                  <div class="text-neutral-400 font-light">
                    <p> Max 20 files </p>
                    <p> Max 50mb single file </p>
                    <p> Max 250mb all files </p>
                    <p> Accepted formats: .mp4, .gif, .png, .jpg, .webm. .mkv, .webp </p>
                  </div>
                </div>
              </div>
            </template>
          </FileUpload>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.p-fileupload-advanced {
    height: 100%;
}

.p-fileupload-content {
    height: 100% !important;
}
</style>
